<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
CREATE TABLE "STUDY"."COUPON" 
   (	"CSEQ" NUMBER(*,0) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(20), 
	"DISCOUNT" VARCHAR2(20), 
	"ID" VARCHAR2(20), 
	 CONSTRAINT "COUPON_PK" PRIMARY KEY ("CSEQ"))
	 
   COMMENT ON COLUMN "STUDY"."COUPON"."CSEQ" IS '쿠폰번호';
   COMMENT ON COLUMN "STUDY"."COUPON"."CONTENT" IS '쿠폰내용';
   COMMENT ON COLUMN "STUDY"."COUPON"."DISCOUNT" IS '할인금액';
   COMMENT ON COLUMN "STUDY"."COUPON"."ID" IS '아이디';
   COMMENT ON TABLE "STUDY"."COUPON"  IS '쿠폰';



CREATE TABLE "STUDY"."P_BOARD" 
   (	"PSEQ" NUMBER(*,0) NOT NULL ENABLE, 
	"PNUM" NUMBER(*,0), 
	"PCONTENT" VARCHAR2(20), 
	"PDATE" DATE, 
	"PTITLE" VARCHAR2(100), 
	 CONSTRAINT "P_BOARD_PK" PRIMARY KEY ("PSEQ"))
	 
   COMMENT ON COLUMN "STUDY"."P_BOARD"."PSEQ" IS '상품게시글번호';
   COMMENT ON COLUMN "STUDY"."P_BOARD"."PNUM" IS '상품번호';
   COMMENT ON COLUMN "STUDY"."P_BOARD"."PCONTENT" IS '내용';
   COMMENT ON COLUMN "STUDY"."P_BOARD"."PDATE" IS '게시날짜';
   COMMENT ON COLUMN "STUDY"."P_BOARD"."PTITLE" IS '제목';
   COMMENT ON TABLE "STUDY"."P_BOARD"  IS '상품게시판';



CREATE TABLE "STUDY"."P_CATEGORY" 
   (	"CNUM" NUMBER(*,0) NOT NULL ENABLE, 
	"PTYPE" VARCHAR2(100), 
	"PCOLOR" VARCHAR2(100), 
	"PSIZE" VARCHAR2(100), 
	 CONSTRAINT "P_CATEGORY_PK" PRIMARY KEY ("CNUM"))
	 
	 
   COMMENT ON COLUMN "STUDY"."P_CATEGORY"."CNUM" IS '카테고리번호';
   COMMENT ON COLUMN "STUDY"."P_CATEGORY"."PTYPE" IS '형태';
   COMMENT ON COLUMN "STUDY"."P_CATEGORY"."PCOLOR" IS '색상';
   COMMENT ON COLUMN "STUDY"."P_CATEGORY"."PSIZE" IS '사이즈';
   COMMENT ON TABLE "STUDY"."P_CATEGORY"  IS '상품분류';


SELECT CSEQ, CONTENT, DISCOUNT, ID FROM COUPON 

SELECT PSEQ, PNUM, PCONTENT, PDATE, PTITLE FROM P_BOARD

SELECT CNUM, PTYPE, PCOLOR, PSIZE FROM P_CATEGORY


</body>
</html>