<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>

</body>
</html>



CREATE TABLE "Q_BOARD" 
   ("QSEQ" int NOT NULL, 
   "QTITLE" VARCHAR2(20) NULL, 
   "QCONTENT" VARCHAR2(20) NULL, 
   "PSEQ" INT NULL, 
   "ID" VARCHAR2(20) NULL,
    CONSTRAINT "Q_BOARD_PK" PRIMARY KEY ("QSEQ"),
    )
    
CREATE SEQUENCE Q_BOARD_SEQ
START WITH 1
INCREMENT BY 1;

SELECT QSEQ, QTITLE, QCONTENT, PSEQ, ID
FROM Q_BOARD;

INSERT INTO Q_BOARD
(QSEQ, QTITLE, QCONTENT, PSEQ, ID)
VALUES(1, '테스트제목', '테스트내용', 1, 'KIM');

UPDATE Q_BOARD
SET QTITLE='문의게시판', QCONTENT='문의내용', PSEQ=1, ID='KIM'
WHERE QSEQ=1;

DELETE FROM Q_BOARD
WHERE QSEQ=2;







CREATE TABLE "R_BOARD"
	("RSEQ" INT NOT NULL, 
    "RTITLE" VARCHAR2(20) NULL, 
    "RCONTENT" VARCHAR2(20) NULL, 
    "PSEQ" INT NULL, 
    "ID" VARCHAR2(20) NULL, 
    "STARRANK" INT NULL,
    CONSTRAINT "R_BOARD_PK" PRIMARY KEY ("RSEQ")
	)


CREATE SEQUENCE R_BOARD_SEQ
START WITH 1
INCREMENT BY 1;

SELECT RSEQ, RTITLE, RCONTENT, PSEQ, ID, STARRANK
FROM R_BOARD;

INSERT INTO R_BOARD
(RSEQ, RTITLE, RCONTENT, PSEQ, ID, STARRANK)
VALUES(1, '리뷰테스트', '립테', 1, 'RV', 5);

UPDATE R_BOARD
SET RTITLE='리뷰게시판', RCONTENT='리뷰내용', PSEQ=1, ID='KIM', STARRANK=4
WHERE RSEQ=1;

DELETE FROM STUDY.R_BOARD
WHERE RSEQ=2;







CREATE TABLE "E_BOARD"
	("ESEQ" INT NOT NULL, 
    "ECONTENT" VARCHAR2(20) NULL, 
    "ETITLE" VARCHAR2(20) NULL, 
    CONSTRAINT "E_BOARD_PK" PRIMARY KEY ("ESEQ")
	)


CREATE SEQUENCE E_BOARD_SEQ
START WITH 1
INCREMENT BY 1;

SELECT ESEQ, ECONTENT, ETITLE
FROM E_BOARD;

INSERT INTO E_BOARD
(ESEQ, ECONTENT, ETITLE)
VALUES(1, '이테', '이벤트테스트');

UPDATE E_BOARD
SET ECONTENT='이벤트내용', ETITLE='이벤트게시판'
WHERE ESEQ=1;

DELETE FROM E_BOARD
WHERE ESEQ=3;

